export const Component = {
  RestApplication: Symbol.for('RestApplication'),
  Logger: Symbol.for('Logger'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  UserService: Symbol.for('UserService'),
  UserModel: Symbol.for('UserModel'),
  TypeService: Symbol.for('TypeService'),
  TypeModel: Symbol.for('TypeModel'),
  FacilityService: Symbol.for('FacilityService'),
  FacilityModel: Symbol.for('FacilityModel'),
  CoordinateService: Symbol.for('CoordinateService'),
  CoordinateModel: Symbol.for('CoordinateModel'),
  CommentService: Symbol.for('CommentService'),
  CommentModel: Symbol.for('CommentModel'),
  OfferService: Symbol.for('OfferService'),
  OfferModel: Symbol.for('OfferModel'),
} as const;
