export const Component = {
  RestApplication: Symbol.for('RestApplication'),
  Logger: Symbol.for('Logger'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  UserService: Symbol.for('UserService'),
  UserModel: Symbol.for('UserModel'),
  UserController: Symbol.for('UserController'),
  TypeService: Symbol.for('TypeService'),
  TypeModel: Symbol.for('TypeModel'),
  TypeController: Symbol.for('TypeController'),
  CityService: Symbol.for('CityService'),
  CityModel: Symbol.for('CityModel'),
  FacilityService: Symbol.for('FacilityService'),
  FacilityModel: Symbol.for('FacilityModel'),
  FacilityController: Symbol.for('FacilityController'),
  CommentService: Symbol.for('CommentService'),
  CommentModel: Symbol.for('CommentModel'),
  OfferService: Symbol.for('OfferService'),
  OfferModel: Symbol.for('OfferModel'),
  OfferController: Symbol.for('OfferController'),
  FavoriteService: Symbol.for('FavoriteService'),
  FavoriteModel: Symbol.for('FavoriteModel'),
  FavoriteController: Symbol.for('FavoriteController'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
} as const;
